build:
  environment:
    php:
      version: '8.2'
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - 'tests/'
    - 'upgrade/tests/'
    - 'extras/'
    - 'docs/'
    - 'htdocs/xoops_lib/vendor/'
    - 'htdocs/install/'

tools:
  php_analyzer: true
