/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './theme.tpl',
        './tpl/**/*.tpl',
        './modules/**/*.tpl',
    ],
    theme: {
        extend: {
            fontFamily: {
                display: ['"Space Grotesk"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                body: ['"Inter"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
            },
            boxShadow: {
                velvet: '0 24px 80px -30px rgba(15, 23, 42, 0.45)',
                float: '0 20px 40px -24px rgba(14, 116, 144, 0.45)',
            },
            borderRadius: {
                shell: '1.75rem',
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('daisyui'),
    ],
    daisyui: {
        themes: [
            {
                atelier: {
                    primary: '#0f766e',
                    'primary-content': '#f2fffd',
                    secondary: '#d97706',
                    'secondary-content': '#fff8ef',
                    accent: '#7c3aed',
                    'accent-content': '#f8f4ff',
                    neutral: '#1f2937',
                    'neutral-content': '#f8fafc',
                    'base-100': '#fcfbf7',
                    'base-200': '#f4efe4',
                    'base-300': '#e8dfcf',
                    'base-content': '#1b2431',
                    info: '#0ea5e9',
                    success: '#15803d',
                    warning: '#d97706',
                    error: '#b91c1c',
                },
            },
            {
                fjord: {
                    primary: '#1d4ed8',
                    'primary-content': '#eff6ff',
                    secondary: '#0f766e',
                    'secondary-content': '#ecfeff',
                    accent: '#9333ea',
                    'accent-content': '#faf5ff',
                    neutral: '#1e293b',
                    'neutral-content': '#f8fafc',
                    'base-100': '#f7fafc',
                    'base-200': '#edf3f8',
                    'base-300': '#dbe6ee',
                    'base-content': '#172033',
                    info: '#0284c7',
                    success: '#15803d',
                    warning: '#ca8a04',
                    error: '#b91c1c',
                },
            },
            {
                pulsefire: {
                    primary: '#c2410c',
                    'primary-content': '#fff7ed',
                    secondary: '#7c2d12',
                    'secondary-content': '#fff7ed',
                    accent: '#be185d',
                    'accent-content': '#fff1f2',
                    neutral: '#292524',
                    'neutral-content': '#fef7ed',
                    'base-100': '#fff8f1',
                    'base-200': '#fdebd8',
                    'base-300': '#f5d6b8',
                    'base-content': '#2f2218',
                    info: '#0f766e',
                    success: '#15803d',
                    warning: '#d97706',
                    error: '#b91c1c',
                },
            },
            {
                noctis: {
                    primary: '#67e8f9',
                    'primary-content': '#0b1120',
                    secondary: '#f59e0b',
                    'secondary-content': '#0b1120',
                    accent: '#c084fc',
                    'accent-content': '#0b1120',
                    neutral: '#101826',
                    'neutral-content': '#e5eef7',
                    'base-100': '#0b1120',
                    'base-200': '#111b2e',
                    'base-300': '#18243b',
                    'base-content': '#d7e3f4',
                    info: '#38bdf8',
                    success: '#4ade80',
                    warning: '#fbbf24',
                    error: '#f87171',
                },
            },
            {
                velvet: {
                    primary: '#f472b6',
                    'primary-content': '#250714',
                    secondary: '#8b5cf6',
                    'secondary-content': '#f5f3ff',
                    accent: '#f59e0b',
                    'accent-content': '#1f1300',
                    neutral: '#190d1f',
                    'neutral-content': '#f8f0ff',
                    'base-100': '#120a18',
                    'base-200': '#1a1023',
                    'base-300': '#261431',
                    'base-content': '#efe4fb',
                    info: '#38bdf8',
                    success: '#4ade80',
                    warning: '#fbbf24',
                    error: '#fb7185',
                },
            },
            {
                graphite: {
                    primary: '#e2e8f0',
                    'primary-content': '#0f172a',
                    secondary: '#38bdf8',
                    'secondary-content': '#082f49',
                    accent: '#f59e0b',
                    'accent-content': '#111827',
                    neutral: '#111827',
                    'neutral-content': '#f8fafc',
                    'base-100': '#0f172a',
                    'base-200': '#172033',
                    'base-300': '#243146',
                    'base-content': '#dbe4f0',
                    info: '#38bdf8',
                    success: '#4ade80',
                    warning: '#fbbf24',
                    error: '#f87171',
                },
            },
        ],
        darkTheme: 'noctis',
        logs: false,
    },
};
